### ISSUE TITLE
roxygen2のコメント行を追加

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#1]
.から始まる関数以外は全てexportする（ユーザーが使う）想定なので、全てroxygen2のコメントをつけてください。
また、適切にNAMESPACEにimport/exportが反映されているか、ヘルプファイルが出力されているかを確認してください。

**Comment by kokitsuyuzaki** [comment]
ちなみにこのdistオプションは、Rの標準関数の距離を返すdistと競合したため、distanceに変えました
https://github.com/rikenbit/WormTensor/blob/c1583938115d420a071a2aad6a2b3473c23e988e/R/worm_download.R#L3

**Comment by yamaken37** [comment]
roxygen2のコメント行を追加し、NAMESPACEにimport/exportが反映され、man/以下にヘルプファイルが作成されていることを確認
https://github.com/rikenbit/WormTensor/blob/492d12eb47d8c6368dc7cc70056ed55291d4785e/NAMESPACE#L1-L30
