### ISSUE TITLE
install_githubの動作確認

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#10]
Issue 1 - 8
https://github.com/rikenbit/WormTensor/issues/1
https://github.com/rikenbit/WormTensor/issues/2
https://github.com/rikenbit/WormTensor/issues/3
https://github.com/rikenbit/WormTensor/issues/4
https://github.com/rikenbit/WormTensor/issues/5
https://github.com/rikenbit/WormTensor/issues/6
https://github.com/rikenbit/WormTensor/issues/7
https://github.com/rikenbit/WormTensor/issues/8

全てに対応できた後のパッケージに対して、

```
devtools::install_github("rikenbit/WormTensor")
```
が正常に動作するか確認

**Comment by yamaken37** [comment]
devtools::install_github(“rikenbit/WormTensor")が正常に動作することを確認。commit：https://github.com/rikenbit/WormTensor/commit/f11c7036dbdc47d68aae057792237b70a8f104f9
GitHubからインストールしたWormTensorパッケージで下記コードも動作
```
worm_download()$Ds |>
    as_worm_tensor() |>
        worm_membership(k=6) |>
            worm_clustering() |>
                worm_evaluate() |>
                    worm_visualize() -> object
```
テストを追加したら再度確認する

**Comment by yamaken37** [comment]
#14 リファクタリング実行後に再度確認。問題なし
