### ISSUE TITLE
CRANへ投稿・受理

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#11]
Issue 1 - 10
https://github.com/rikenbit/WormTensor/issues/1
https://github.com/rikenbit/WormTensor/issues/2
https://github.com/rikenbit/WormTensor/issues/3
https://github.com/rikenbit/WormTensor/issues/4
https://github.com/rikenbit/WormTensor/issues/5
https://github.com/rikenbit/WormTensor/issues/6
https://github.com/rikenbit/WormTensor/issues/7
https://github.com/rikenbit/WormTensor/issues/8
https://github.com/rikenbit/WormTensor/issues/9
https://github.com/rikenbit/WormTensor/issues/10

全てに対応できた後のパッケージをCRANに投稿する。

CRAN側からのコメントに対応し、受理してもらう。

最終的に以下のリンク先にWormTensorが配置されたことを最後に確認する。
https://cran.r-project.org/web/packages/WormTensor

**Comment by yamaken37** [comment]
CRAN Comment　8月26日(金) 16:49

下記の６つの点を対応してほしいとのメッセージが来た
【NOTE】DESCRIPTIONの修正
【NOTE】メールアドレスが違う
【ERROR】exampleのコード実行時にworm_downloadでエラー＠windows環境
【ERROR】tests/testthat.R’のテストの実行に失敗＠windows環境
【ERROR】vignettesの再構築に失敗＠windows環境
【NOTE】Examples with CPU (user + system) or elapsed time＠linux環境

**Comment by yamaken37** [comment]
CRANから
`on its way to CRAN.`の返信が来て、
以下のリンク先にWormTensorが配置されたことが確認できた。
https://cran.r-project.org/web/packages/WormTensor
