### ISSUE TITLE
Dockerイメージ作成

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#12]
CRANに投稿したパッケージ（https://github.com/rikenbit/WormTensor/issues/11 ）がインストールされたDockerイメージ（yamaken37/wormtensor）を作成。

最終的に以下のページに配置されたことを確認。
https://hub.docker.com/r/yamaken37/wormtensor

**Comment by yamaken37** [comment]
メモ
GitHubActions運用で作成した方が良さそう。

**Comment by kokitsuyuzaki** [comment]
cf.
https://github.com/rikenbit/OnlinePCA.jl/blob/master/.github/workflows/build_push.yml

**Comment by yamaken37** [comment]
cf.　Docker研修の
https://github.com/yamaken37/reproducible-tools-exercise-r/blob/main/.github/workflows/build_push_test.yml

**Comment by yamaken37** [comment]
Dockerイメージ作成用のリポジトリ [yamaken37/WormTensor_Docker](https://github.com/yamaken37/WormTensor_Docker)を用意。
GitHubActionsの自動ビルドにより、GHCRとDockerHubの両方にDockerイメージ作成。
* [GHCR](https://github.com/yamaken37/WormTensor_Docker/pkgs/container/wormtensor)
* [Docker Hub](https://hub.docker.com/repository/docker/yamaken37/wormtensor)

GHCR、Docker HubにGitHubのcommit ID「sha-def2ba9」をtagに入れたイメージを作成。
これらのDockerイメージを用いてWormTensorパッケージのPipe Operationを実行できた。
