### ISSUE TITLE
リファクタリング

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#14]
- コーディングスタイル: lintr, stylerを使用
- コードのtidy化: 関数に関数が被さっているところ、中間オブジェクトが発生しているところは、パイプで繋ぐ書き方に変更（ただし、tidyverseを依存パッケージに入れるのはトラブルを引き起こす可能性があるため、R's Native Pipe（|>）を使用
   e.g., https://github.com/rikenbit/WormTensor/blob/c1583938115d420a071a2aad6a2b3473c23e988e/R/worm_clustering.R#L77-L78
https://github.com/rikenbit/WormTensor/blob/a4c8da3d3ef14162638646b5865e428d8e158b3c/R/as_worm_tensor.R#L12-L14
https://github.com/rikenbit/WormTensor/blob/a4c8da3d3ef14162638646b5865e428d8e158b3c/R/worm_membership.R#L13
https://github.com/rikenbit/WormTensor/blob/a4c8da3d3ef14162638646b5865e428d8e158b3c/R/worm_membership.R#L54

**Comment by yamaken37** [comment]
CRAN投稿前に対応
・パイプ
・日本語→英語
など

**Comment by yamaken37** [comment]
リファクタリングし、再度 #9 #10 実行したが問題なし、パッケージインストールして、Pipe Operationもちゃんと動作した
