### ISSUE TITLE
非対称行列のテスト

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#15]
これはas.matrix自体のテストになってしまっているから省略
https://github.com/rikenbit/WormTensor/blob/master/tests/testthat/test-worm_distance.R

**Comment by kokitsuyuzaki** [comment]
S4クラスの定義の段階で、I×I×Mのメンバーシップ行列の各Frontal Slice（I×I）が対称になっているかをチェックすべき（setClassのvalidityオプション）
https://stackoverflow.com/questions/38375880/validity-check-of-s4-class-in-r

**Comment by kokitsuyuzaki** [comment]
as.worm_tensorのところで

```r
.check_as_worm_tensor <- function(Ds){
    lapply(Ds, function(x){
    	stopifnot(is(x) == "dist")
    })
}
```

として

```
.check_as_worm_tensor(Ds)
```

をDsをWormTensorオブジェクトに格納する前の段階で実行すれば、このテストは不要

**Comment by yamaken37** [comment]
test-as_worm_tensor.Rに書き込むテスト。
ユーザーがおれおれ距離行列（リスト）をつっこんだときに、距離行列になってるとうれしい。
距離行列以外（リスト）のものがas_worm_tensorの引数に渡されないようにするためのチェック

**Comment by yamaken37** [comment]
.check_as_worm_tensor追加(commit: https://github.com/rikenbit/WormTensor/commit/9e35f2c0eebc363f27678d6ddb802a2cfbdc2d5e )

https://github.com/rikenbit/WormTensor/blob/9e35f2c0eebc363f27678d6ddb802a2cfbdc2d5e/R/as_worm_tensor.R#L11-L14
https://github.com/rikenbit/WormTensor/blob/9e35f2c0eebc363f27678d6ddb802a2cfbdc2d5e/R/as_worm_tensor.R#L31-L35
