### ISSUE TITLE
DESCRIPTIONファイルの編集

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#16]
- 英語が冗長なので、以下のように直してください。

Title: A clustering method for time-series whole-brain activity data of C. elegans

Description: A toolkit to detect clusters from distance matrices. The distance matrices are assumed to be calculated between the cells of multiple animals (Caenorhabditis elegans) from input time-series matrices. Some functions for generating distance matrices, performing clustering, evaluating the clustering, and visualizing the results of clustering and evaluation are available. We're also providing the download function to retrieve the pre-calculated distance matrices from figshare.

- R Native Pipeを使うため、DependsのところにRのバージョンは4.1.0以上と指定してください。
cf.
https://www.r-bloggers.com/2021/05/the-new-r-pipe/
https://github.com/rikenbit/nnTensor/blob/cf0b5fb69e533e849637bb2570387646a4227203/DESCRIPTION#L11

**Comment by yamaken37** [comment]
Title、Description、Depends修正しました。
https://github.com/rikenbit/WormTensor/blob/0d0f4dfb551a336a27dc5ae5ad1223511ebf8af0/DESCRIPTION#L3
https://github.com/rikenbit/WormTensor/blob/0d0f4dfb551a336a27dc5ae5ad1223511ebf8af0/DESCRIPTION#L10
https://github.com/rikenbit/WormTensor/blob/0d0f4dfb551a336a27dc5ae5ad1223511ebf8af0/DESCRIPTION#L25

また、Importsも記載しました。
https://github.com/rikenbit/WormTensor/blob/0d0f4dfb551a336a27dc5ae5ad1223511ebf8af0/DESCRIPTION#L26

**Comment by kokitsuyuzaki** [comment]
忘れてましたが、TitleはTitle Caseにしないとなので、以下のようにしてください

```
Title: A Clustering Method for Time-Series Whole-Brain Activity Data of C. elegans
```

**Comment by yamaken37** [comment]
Title Caseに修正しました
https://github.com/rikenbit/WormTensor/blob/ec60d5ce22f07806d557805d4faf72554f1d663f/DESCRIPTION#L3
