### ISSUE TITLE
README.mdにバッジを追加

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#17]
CRAN, Zenodo, bioRxiv, Altmetricなど

cf.
https://github.com/TomKellyGenetics/graphsim

**Comment by yamaken37** [comment]
CRAN, Zenodoのバッジ追加

<img width="551" alt="スクリーンショット 2022-09-09 18 46 26" src="https://user-images.githubusercontent.com/58546728/189322404-abc26cab-9840-4725-b753-573a13a0385b.png">
