### ISSUE TITLE
LICENSEファイルの編集

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#18]
研修資料で間違ったことを伝えてしまったかもしれませんが、`usetthis::use_mit_license("WormTensor")`ではなく、`usetthis::use_mit_license("Kentaro Yamamoto")`としてください。

ここには自分の名前が入っている必要があります。
https://github.com/rikenbit/WormTensor/blob/master/LICENSE

**Comment by yamaken37** [comment]
パッケージ名記入するとこだと勘違いしていました。
`usetthis::use_mit_license("Kentaro Yamamoto")`で自分の名前に修正しました。
https://github.com/rikenbit/WormTensor/blob/9e81dcf5a55005c2cfc64689f914d141e29c6e3d/LICENSE#L2
https://github.com/rikenbit/WormTensor/blob/9e81dcf5a55005c2cfc64689f914d141e29c6e3d/LICENSE.md
