### ISSUE TITLE
worm_download関数の修正

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#19]
細胞名の変更に伴い、Figshareにデータを置き直すため、以下のURLを書き換える必要がある。
https://github.com/rikenbit/WormTensor/blob/394b3fa203b718783add6bd333a88f032cd29761/R/worm_download.R#L25
https://github.com/rikenbit/WormTensor/blob/394b3fa203b718783add6bd333a88f032cd29761/R/worm_download.R#L29
https://github.com/rikenbit/WormTensor/blob/394b3fa203b718783add6bd333a88f032cd29761/R/worm_download.R#L46

**Comment by kokitsuyuzaki** [comment]
以下のURLに変更
- Euclid.RData: https://figshare.com/ndownloader/files/35963777
- mSBD.RData: https://figshare.com/ndownloader/files/35963780
- ラベル情報（CSV）: https://figshare.com/ndownloader/files/35940755

**Comment by yamaken37** [comment]
URL変更しました

- Euclid.RData
https://github.com/rikenbit/WormTensor/blob/c54c3c7857a4fee387df6a3b422b1cf6f8a38afa/R/worm_download.R#L29
- mSBD.RData
https://github.com/rikenbit/WormTensor/blob/c54c3c7857a4fee387df6a3b422b1cf6f8a38afa/R/worm_download.R#L25
- ラベル情報（CSV）
https://github.com/rikenbit/WormTensor/blob/c54c3c7857a4fee387df6a3b422b1cf6f8a38afa/R/worm_download.R#L46

**Comment by yamaken37** [comment]
EuclidのURL（余計な半角スペース）に誤りがあったので修正しました

- Euclid.RData

https://github.com/rikenbit/WormTensor/blob/4817b3adc68f9a97cb7a09e08f60f95f241b90c6/R/worm_download.R#L28
