### ISSUE TITLE
NEWSファイルの作成

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#2]
以下を参考
https://bookdown.org/yutannihilation/practical-r-package-development-ja/r.html#news.md
https://github.com/rikenbit/nnTensor/blob/master/inst/NEWS

**Comment by yamaken37** [comment]
NEWSファイルを生成できた(commit：https://github.com/rikenbit/WormTensor/commit/0e77b22df4dd0ce06c331aae3f8708bc8da77604 )
