### ISSUE TITLE
worm_visualize関数の実装_次元削減オプションを引数に追加

### ISSUE THREAD

**Issue by yamaken37** [rikenbit/WormTensor#21]
tSNEやUMAPのオプションも引数として受け取れるようにする。デフォルト値はデータ解析のやつ。
set.seedも引数に足す。
引数追加に伴いAllGenerics.Rに数値チェックとか足す。

**Comment by yamaken37** [comment]
引数を追加。追加した引数を設定しての実行もできることを確認。
https://github.com/rikenbit/WormTensor/blob/d0494ee6101a1716616921a7784cdced75eed6a9/R/AllGenerics.R#L26-L37
https://github.com/rikenbit/WormTensor/blob/d0494ee6101a1716616921a7784cdced75eed6a9/R/worm_visualize.R#L43-L53
https://github.com/rikenbit/WormTensor/blob/d0494ee6101a1716616921a7784cdced75eed6a9/R/worm_visualize.R#L57-L66
https://github.com/rikenbit/WormTensor/blob/d0494ee6101a1716616921a7784cdced75eed6a9/R/worm_visualize.R#L350-L359

**Comment by kokitsuyuzaki** [comment]
verbose系はデフォルトでFALSEにする

**Comment by yamaken37** [comment]
verbose系をデフォルトでFALSEにし、実行の詳細が表示されないようにした。
https://github.com/rikenbit/WormTensor/blob/13a07655a92513ca6caa1450a486f4af38b44451/R/AllGenerics.R#L33
https://github.com/rikenbit/WormTensor/blob/13a07655a92513ca6caa1450a486f4af38b44451/R/AllGenerics.R#L37

**Comment by yamaken37** [comment]
対応済み。
ggplotの実行メッセージもでないようにした。(commit: https://github.com/rikenbit/WormTensor/commit/02f90300745b54d2a5e090ae0ba3d5be83b24911 )
