### ISSUE TITLE
隠しファイルのチェック

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#23]
以下のようなファイルは、GitHub上にもRパッケージ内部でも入っていてはいけないので、.gitignoreや.rbuildignoreなどで対応してください

- "._"で始まる隠しファイル: Macでsshfs越しにファイルを開くと発生する
- .DS_Store: MacのFINDER越しにファイルを開くと発生する

**Comment by yamaken37** [comment]
._や.DS_Storeを.ignoreに設定、vignettes配下に混入していた._で始まる隠しファイルも削除(commit: https://github.com/rikenbit/WormTensor/commit/55a4b1780278718a5aa7133b813ee4dfa270f76f )
