### ISSUE TITLE
Suboptimal check of `dist`

### ISSUE THREAD

**Issue by asardaes** [rikenbit/WormTensor#24]
Hi there, I'm the developer of the `dtwclust` package. I'm doing some refactoring and one change I need to do is to call `setOldClass("dist")` in my package, which means any `dist` object will then return 2 elements when calling `class`: "dist" and "oldClass". This breaks the check you do in `as_worm_tensor`:

https://github.com/rikenbit/WormTensor/blob/48e2348a546ae19cbef6e28d0b52ee3dadc6f98b/R/as_worm_tensor.R#L37

To prevent issues, you should change the check to call `is(x, "dist")`.

cc @yamaken37

**Comment by yamaken37** [comment]
@asardaes 
Thank you [asardaes](https://github.com/asardaes)!
Your suggested issue is correct and it is a simple fix, I will discuss it with WormTensor members and fix it quickly.

WormTensor is assisted by the dtwclust package in the creation of the distance matrix.
I would like to thank you again. Thank you！

**Comment by yamaken37** [comment]
@asardaes 
I merged your issue!
I will close this issue.

**Comment by asardaes** [comment]
Thanks a lot :)

**Comment by asardaes** [comment]
Hi @yamaken37, would you be able to submit the fixed version to CRAN? I'm trying to submit the `dtwclust` update and the reverse dependency checks are failing.

**Comment by yamaken37** [comment]
Hi @asardaes ,Sorry, I hadn't updated the CRAN one yet.
We will respond as soon as possible!

**Comment by yamaken37** [comment]
Hi @asardaes ,
WormTensor 0.1.1 has been resubmitted.
The Debian version passed the tests, but the Windows version failed.
Please wait a little longer for the CRAN update.

Windows: <https://win-builder.r-project.org/incoming_pretest/WormTensor_0.1.1_20240723_072431/Windows/00check.log>
Status: 1 ERROR
Debian: <https://win-builder.r-project.org/incoming_pretest/WormTensor_0.1.1_20240723_072431/Debian/00check.log>
Status: OK

**Comment by yamaken37** [comment]
Hi @asardaes 

I submit the fixed version to CRAN.

WormTensor 0.1.1 published.

https://cran.r-project.org/web/packages/WormTensor/index.html

**Comment by asardaes** [comment]
Thank you!
