### ISSUE TITLE
README.mdファイルの作成

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#3]
以下を参考
https://bookdown.org/yutannihilation/practical-r-package-development-ja/r.html#readme.rmd
https://github.com/rikenbit/nnTensor

**Comment by yamaken37** [comment]
nnTensorを参考にREADMEファイルを作成。ライセンスはMIT License（commit:https://github.com/rikenbit/WormTensor/commit/69c437706fa143024961f47caafbf90fdf00ed5b ）
