### ISSUE TITLE
worm_visualize関数の実装

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#4]
論文のFigを再現できるように、画像出力部分を実装
https://github.com/rikenbit/WormTensor/blob/c1583938115d420a071a2aad6a2b3473c23e988e/R/worm_visualize.R#L27-L33

**Comment by kokitsuyuzaki** [comment]
Consistencyや、No. of identified cellsの値はworm_evaluateの結果を利用する
https://github.com/rikenbit/WormTensor/issues/5

**Comment by yamaken37** [comment]
メモ
各細胞のシルエット係数に計算は`silhouette(クラスタリング結果, クラスタリングに用いたデータの距離行列)`
クラスタリングに用いたデータの距離行列がWormTensorオブジェクトのスロットに含まれていない。
・MCMI
WormTensorオブジェクト（object）の
`object@factor`が行列Uに該当するので`dist(U)`、つまり`dist(object@factor)`をすれば、クラスタリングに用いたデータの距離行列。
・OINDSCAL
同様に`dist(object@factor)`
・CSPA
`as.dist(1 - object@consensus)`

`object@clustering_algorithm`の値に応じて、どうやって距離行列を用意するか変えないといけない

**Comment by kokitsuyuzaki** [comment]
終わったと思われるが、install_githubが動かないのでまだ試していない
https://github.com/rikenbit/WormTensor/issues/10

**Comment by kokitsuyuzaki** [comment]
out.dirを指定して、かつパイプで処理する場合のworm_visualizeの引数の渡し方ってどうしてますか？
このFigの通りに動きますか？
![Figure8](https://user-images.githubusercontent.com/2173745/183791713-a9b5a745-6f64-4b99-b8eb-05e359755ded.png)

**Comment by yamaken37** [comment]
このFigの通りには動きません。
`worm_visualize`の第２引数は`algorithm`なので、`worm_evaluate() |> worm_visualize(out.dir)`とすると、"tSNE"か "UMAP"を指定するところに`out.dir`を入れることになるので、エラーになります。

現状のコードでは、ユーザーの指定したディレクトリに出力するには、`out.dir=`で指定する必要があります。
```
    worm_evaluate() |>
    worm_visualize(out.dir=out.dir) -> object
```
※何も指定しなかった場合`worm_visualize()`のout.dirはtemdir()に設定される。

 `worm_visualize`でユーザー側で設定することが一番多いのは`out.dir`（出力先）になると思うので、
 `out.dir`を第２引数に変更し、下記コードで動くようにしたほうが良い。
```
    worm_evaluate() |>
    worm_visualize(out.dir) -> object
```
 いちいち `out.dir=`を書く手間がなくなる。
 
 第２引数を`out.dir`に変更し、上記Figの通りに動く`worm_visualize`に修正します。

**Comment by kokitsuyuzaki** [comment]
RのNative Pipeの詳細をあまり追えてないのですが、第1引数はパイプから渡されたオブジェクトで、第2がout.dirのように陽にユーザーによって渡されたオブジェクト、ということでしょうか？

**Comment by yamaken37** [comment]
はい、そうです。
第1引数はパイプから渡されたオブジェクトで、第2がout.dirのように陽にユーザーによって渡されたオブジェクトということです。
そのように使えるように修正しました。R CMD checkで現在動作確認しています。

**Comment by yamaken37** [comment]
worm_visualizeの引数の順番変更。(commit: https://github.com/rikenbit/WormTensor/commit/5866e735f8f78a1b4634a0205b4654c352879a8e )
R CMD checkでもworm_visualizeに関するエラーがないことを確認。

**Comment by yamaken37** [comment]
issue https://github.com/rikenbit/WormTensor/issues/6 でも修正が入らず、`R CMD check`も`R CMD check succeeded`だったので、これ以降大規模な修正は入らないと思われるのでclose
