### ISSUE TITLE
worm_evaluate関数の実装

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#5]
## 細胞ごとのスコアを実装
- Consistency（consistencyという名前のベクトルにする）
- No. of identified cells（no_identifiedという名前のベクトルにする）
- Silhouette係数（silhouetteという名前のベクトルにする）

これらを以下の位置に配置
https://github.com/rikenbit/WormTensor/blob/c1583938115d420a071a2aad6a2b3473c23e988e/R/worm_evaluate.R#L17-L19

cellwiseというリストにこれら3つベクトルを格納
```
cellwise <- list(consistency=consistency,
    no_identified=no_identified,
    silhouette=silhouette)
```

最後に以下のようにobject@evalに登録
```
object@eval <- list(internal=int_out, external=ext_out, cellwise=cellwise)
```
https://github.com/rikenbit/WormTensor/blob/c1583938115d420a071a2aad6a2b3473c23e988e/R/worm_evaluate.R#L38-L39

## Internal Validity Indicesの一つとして、個体ごとの平均Silhouette係数を追加

cellwise$silhouetteの平均をとって、int_outリストにsilhouetteとして追加
https://github.com/rikenbit/WormTensor/blob/c1583938115d420a071a2aad6a2b3473c23e988e/R/worm_evaluate.R#L23

**Comment by yamaken37** [comment]
メモ
各細胞のシルエット係数に計算はsilhouette(クラスタリング結果, クラスタリングに用いたデータの距離行列)
クラスタリングに用いたデータの距離行列がWormTensorオブジェクトのスロットに含まれていない。
・MCMI
WormTensorオブジェクト（object）の
object@factorが行列Uに該当するのでdist(U)、つまりdist(object@factor)をすれば、クラスタリングに用いたデータの距離行列。
・OINDSCAL
同様にdist(object@factor)
・CSPA
as.dist(1 - object@consensus)

object@clustering_algorithmの値に応じて、どうやって距離行列を用意するか変えないといけない

**Comment by yamaken37** [comment]
メモ
.connectivityがCSPAのケースで`dist(data, method="euclidean")`になっている。
as.dist(1 - object@consensus)に直す。

**Comment by yamaken37** [comment]
worm_evaluate関数の実装した（.connectivityの修正は未済）
https://github.com/rikenbit/WormTensor/blob/7be7af11b376a919770a0bc60199ad7a61443959/R/worm_evaluate.R#L33

**Comment by yamaken37** [comment]
.connectivity修正
object@clustering_algorithmがCSPAのとき、.connectivityの計算で使うの距離行列が`as.dist(1 - object@consensus)`で作成されるようにした。
https://github.com/rikenbit/WormTensor/blob/49ce3509fb0d96def7f471e723d93da1d7ebe123/R/worm_evaluate.R#L74

**Comment by yamaken37** [comment]
consistencyを修正。labelsリストの正解ラベルごとにconsistencyを計算するようにした。以前はlabelsリストの1つ目の正解ラベルだけしか計算していなかった。
（https://github.com/rikenbit/WormTensor/commit/99dddbc5f361086c97580520f14180a9aa1ff3dd# ）
https://github.com/rikenbit/WormTensor/blob/99dddbc5f361086c97580520f14180a9aa1ff3dd/R/worm_evaluate.R#L62

**Comment by kokitsuyuzaki** [comment]
終わったと思われるが、install_githubが動かないのでまだ試していない
https://github.com/rikenbit/WormTensor/issues/10

**Comment by yamaken37** [comment]
issue https://github.com/rikenbit/WormTensor/issues/6 でも修正が入らず、`R CMD check`も`R CMD check succeeded`だったので、これ以降大規模な修正は入らないと思われるので、close
