### ISSUE TITLE
論文の結果の再現

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#6]
以下のようなパイプで、論文の解析が再現できるようにする。
https://github.com/rikenbit/WormTensor/blob/c1583938115d420a071a2aad6a2b3473c23e988e/tests/testthat/test-worm_visualize.R#L4-L10

特に以下のような条件がWormTimeSeriesと揃っているか、適宜チェックする。
- 入力データのサイズ（例: コンセンサス行列、テンソル）
-アルゴリズムのパラメーター（例: CSPA、MCMI、 t-SNE/UMAP）
- Figureのパラメーター（例: 点やラベルのサイズ）

**Comment by kokitsuyuzaki** [comment]
例えば、Figshareにあるlabel（https://figshare.com/articles/dataset/label_table_merged_csv/19368119
）は194細胞ですが、こちらで解析すると507細胞分のデータで解析する処理になってしまうので、細かい部分で違いが出てしまっているため、修正してください。

**Comment by kokitsuyuzaki** [comment]
数字だけの個体を除去していないからだと思われる。
worm_downloadの中で、除去する必要あり。

**Comment by yamaken37** [comment]
メモ：数字だけの個体の除去をworm_downloadの中で実装し、除去後の距離行列のリストが実データと同じになることを確認する

**Comment by yamaken37** [comment]
.filter_cellnames関数を作成し数字だけの個体の除去できるようにした。
https://github.com/rikenbit/WormTensor/blob/42b620d38ee9927dc0c5d3925f0db26f308bd888/R/worm_download.R#L59
worm_download関数の結果できる距離行列と、実データ解析の距離行列がidenticalでTRUEになった。
<img width="266" alt="スクリーンショット 2022-07-04 15 06 20" src="https://user-images.githubusercontent.com/58546728/177091826-406f247b-9648-4f10-ab1c-f8d99f85edaf.png">
引き続き、他の解析ステップにおいても再現できるよう取り組む。

**Comment by yamaken37** [comment]
WormTimeSeriesとWormTensorで結果を比較するポイント
・✅解析に使う距離行列：worm_download()$Ds
・✅メンバーシップ行列・テンソル：worm_membership(k=6)
・✅クラスタリング結果：worm_clustering()
・評価結果：worm_evaluate()
・可視化：worm_visualize()

**Comment by yamaken37** [comment]
・メンバーシップ行列・テンソル：worm_membership(k=6)✅
同じメンバーシップ行列の値になることを確認できた。
![スクリーンショット 2022-08-05 19 28 50](https://user-images.githubusercontent.com/58546728/183059395-6a7646ef-237f-4930-844f-1dff1e5a6d25.png)

**Comment by yamaken37** [comment]
・クラスタリング結果：worm_clustering()✅
下記条件で同一のクラスタリング結果であることを確認
・24個体
・mSBD
・k=6
・MCMI
WormTensorとWormTimeSeriesで、クラスタリング結果のオブジェクトの細胞名の順番や1〜6のクラスタ番号の割り当てが異なってたので、揃えてからidentical()で比較し、TRUEになることを確認。

**Comment by yamaken37** [comment]
下記２つも確認済み（チーム内で確認）
・評価結果：worm_evaluate()
　一定の小数点桁数以上で同一の値
・可視化：worm_visualize()
　同様の結論が導ける次元圧縮図
　
条件
・24個体
・mSBD
・k=6
・MCMI
・UMAP
