### ISSUE TITLE
テスト

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#7]
## worm_evaluateのテスト
このIssueに適切に対応できたかを
https://github.com/rikenbit/WormTensor/issues/5
以下のファイル内でテストする。
https://github.com/rikenbit/WormTensor/blob/master/tests/testthat/test-worm_evaluate.R

# worm_visualizeのテスト
このIssueに適切に対応できたかを
https://github.com/rikenbit/WormTensor/issues/4
以下のファイル内でテストする。
https://github.com/rikenbit/WormTensor/blob/c1583938115d420a071a2aad6a2b3473c23e988e/tests/testthat/test-worm_visualize.R#L12-L26

testthat/以下のテストは全て達るようにする。

**Comment by yamaken37** [comment]
issue https://github.com/rikenbit/WormTensor/issues/6 でも修正が入らず、`R CMD check`も`R CMD check succeeded`だったので、これ以降大規模な修正は入らないと思われるので、close
