### ISSUE TITLE
vignetteの作成

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#8]
use_this::use_vigntteでR markdownファイルを生成。
ファイル内で、WormTensorの簡単なデモンストレーションを行う。
他のパッケージのvignetteを参考にする。
https://bioconductor.org/packages/release/bioc/vignettes/scTensor/inst/doc/scTensor.html

最初に、以下のように、関数ひとつひとつを実行させ、内部で何をしているのかを順序立てて説明

← worm_download()についての説明文 →

```
object <- worm_download()
```

← as_worm_tensor()についての説明文 →

```
object <- as_worm_tensor(object$Ds)
```

最後に、上記のような関数はR's native pipeで連携して処理も可能と説明。
https://github.com/rikenbit/WormTensor/blob/c1583938115d420a071a2aad6a2b3473c23e988e/tests/testthat/test-worm_visualize.R#L4-L10

**Comment by yamaken37** [comment]
vignette作成完了(commit: https://github.com/rikenbit/WormTensor/commit/f323a68a3f3f945a6e666344db8e283c05763dc7 )

**Comment by kokitsuyuzaki** [comment]
as_wormtensorで得られたWormTensorオブジェクトが再度as_wormtensorで使われるわけではないのでは（used forの後）。
https://github.com/rikenbit/WormTensor/blob/9e35f2c0eebc363f27678d6ddb802a2cfbdc2d5e/vignettes/WormTensor.Rmd#L44

**Comment by yamaken37** [comment]
ちょっとよく理解してないかもですが、`as_worm_tensor`の文言を抜いて、下記のようにしたほうがよいのでは？ということでしょうか？

A `WormTensor` object S4 class is used by  `worm_membership`, `worm_clustering`, `worm_evaluate`, and `worm_visualize`.

**Comment by yamaken37** [comment]
`as_worm_tensor`の文言を削除
https://github.com/rikenbit/WormTensor/blob/ba75dd9d994d0e68ad81370b6b9b38a7e014913d/vignettes/WormTensor.Rmd#L44
