### ISSUE TITLE
R CMD BUILD/INSTALL/CHECK

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/WormTensor#9]
Issue 1 - 8
https://github.com/rikenbit/WormTensor/issues/1
https://github.com/rikenbit/WormTensor/issues/2
https://github.com/rikenbit/WormTensor/issues/3
https://github.com/rikenbit/WormTensor/issues/4
https://github.com/rikenbit/WormTensor/issues/5
https://github.com/rikenbit/WormTensor/issues/6
https://github.com/rikenbit/WormTensor/issues/7
https://github.com/rikenbit/WormTensor/issues/8

全てに対応できた後、パッケージに対してR CMD BUILD/INSTALL/CHECKがERROR/NOTE無く全て実行できることを確認、エラーメッセージをよく読み、Google検索で何を言っているのかを調べる。

**Comment by yamaken37** [comment]
`R CMD BUILD`と`R CMD INSTALL`はエラーなしで完了すること確認。
`R CMD CHECK`はERROR/NOTE/WARNINGがあった。対処中。

**Comment by yamaken37** [comment]
R CMD CHECKの未解決問題

1. Error 「theme_half_open()」
2. WARNING「checking for missing documentation entries」
3. WARNING「checking Rd \usage sections」
4. NOTE「checking dependencies in R code」
5. NOTE「checking R code for possible problems」
6. Failed tests「test-worm_evaluate.R」
7. Failed tests「test-worm_visualize.R」

**Comment by yamaken37** [comment]
R CMD CHECKのERROR/NOTE/WARNINGクリア。
R CMD check succeededになった

**Comment by yamaken37** [comment]
vignettesの画像ファイル追加により、ビルド時に作成される`inst/doc/WormTensor.html`の肥大が生じて、
`checking installed package size ... NOTE`のNOTEが生じたので、
画像ファイルのサイズ削減を行い、NOTEを解消した。
(commit: https://github.com/rikenbit/WormTensor/commit/4e7fbb82e59c6ab35fc6b826f6487d57fb4280b9 )
